# The name of this app. Must be unique within a project.
name: app

# The runtime the application uses. The 'type' key defines the base container
# image that will be used to run the application. There is a separate base
# container image for each primary language for the application,
# in multiple versions. Check the Python documentation
# (https://docs.platform.sh/languages/python.html#supported-versions)
# to find the supported versions for the 'python' type.
type: "python:3.11"

# The following block defines a single writable directory, 'web/uploads'
# The 'source' specifies where the writable mount is. The 'local' source
# indicates that the mount point will point to a local directory on the
# application container. The 'source_path' specifies the subdirectory
# from within the source that the mount should point at.
mounts:
  "web/uploads":
    source: local
    source_path: uploads
  "web/static":
    source: local
    source_path: static
  "media":
    source: local
    source_path: media

# The size of the persistent disk of the application (in MB).
disk: 2048

# The relationships of the application with services or other applications.
#
# The left-hand side is the name of the relationship as it will be exposed
# to the application in the PLATFORM_RELATIONSHIPS variable. The right-hand
# side is in the form '<service name>:<endpoint name>'.
relationships:
  postgresdatabase: "postgresql:postgresql"
  redis: "rediscache:redis"

hooks:
  build: |
    mkdir wheels
    pip wheel --wheel-dir wheels -r requirements/production.txt
    pip install --no-cache-dir --no-index --find-links=wheels/ wheels/*  && rm -rf wheels/
    python manage.py collectstatic --noinput

web:
  commands:
    start: "gunicorn -w 4 --access-logfile '-' --error-logfile '-' -b localhost:$PORT config.wsgi:application"
  locations:
    "/static":
      root: "web/static"
      expires: 24h
      passthru: false
      allow: true
    "/media":
      root: "media"
      expires: 24h
      passthru: false
      allow: true
    "/":
      root: "public"
      passthru: true
      allow: false
