version: "3"

volumes:
  cvback_local_postgres_data: {}
  cvback_local_postgres_data_backups: {}
  cvback_local_redis_data: {}

services:
  django: &django
    platform: linux/amd64
    build:
      context: .
      dockerfile: ./compose/local/django/Dockerfile
    image: cvback_local_django
    container_name: cvback_local_django
    depends_on:
      - postgres
    volumes:
      - .:/app:z
    env_file:
      - ./.envs/.local/.django
      - ./.envs/.local/.postgres
    ports:
      - "8000:8000"
    command: /start

  postgres:
    platform: linux/amd64
    build:
      context: .
      dockerfile: ./compose/production/postgres/Dockerfile
    image: cvback_production_postgres
    container_name: cvback_local_postgres
    volumes:
      - cvback_local_postgres_data:/var/lib/postgresql/data
      - cvback_local_postgres_data_backups:/backups
    env_file:
      - ./.envs/.local/.postgres
    ports:
      - "5432:5432"

  redis:
    image: docker.io/redis:6
    container_name: cvback_local_redis

    volumes:
      - cvback_local_redis_data:/data

  celeryworker:
    <<: *django
    image: cvback_local_celeryworker
    container_name: cvback_local_celeryworker
    depends_on:
      - postgres
    ports: []
    command: /start-celeryworker

  celerybeat:
    <<: *django
    image: cvback_local_celerybeat
    container_name: cvback_local_celerybeat
    depends_on:
      - postgres
    ports: []
    command: /start-celerybeat

  flower:
    <<: *django
    image: cvback_local_flower
    container_name: cvback_local_flower
    ports:
      - "5555:5555"
    command: /start-flower

  docs:
    <<: *django
    platform: linux/amd64
    image: cvback_local_docs
    container_name: cvback_local_docs
    build:
      context: .
      dockerfile: ./compose/local/docs/Dockerfile
    env_file:
      - ./.envs/.local/.django
      - ./.envs/.local/.postgres
    volumes:
      - ./docs:/docs:z
      - ./config:/app/config:z
      - ./cvback:/app/cvback:z
    ports:
      - "9000:9000"
    command: /start-docs

  vite:
    build:
      context: .
      dockerfile: ./compose/local/vite/Dockerfile
    image: cvback_local_vite
    container_name: vcback_local_vite
    depends_on:
      - django
    volumes:
      - .:/app:z
      - /app/vue_frontend/node_modules
    command: vite dev
    ports:
      - '5173:5173'

