# Generated by Django 4.2.5 on 2024-05-24 16:13

import cvback.events.models
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django_jsonform.models.fields


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("devices", "0007_camera_last_seen_online_camera_need_cleaning_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Algorithm",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            ("dc", "Detection + classification model"),
                            ("cl", "Classification model"),
                            ("clccv", "Classification classic computer vision"),
                        ],
                        max_length=255,
                    ),
                ),
                ("added_date", models.DateTimeField(auto_now_add=True, verbose_name="date created")),
                ("name", models.CharField(max_length=30)),
                ("version", models.CharField(max_length=30)),
                ("repository", models.CharField(max_length=30, validators=[django.core.validators.URLValidator])),
            ],
        ),
        migrations.CreateModel(
            name="BoundingBox",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("added_date", models.DateTimeField(auto_now_add=True, verbose_name="date created")),
                (
                    "top_left",
                    django_jsonform.models.fields.ArrayField(
                        base_field=models.FloatField(validators=[cvback.events.models.validate_relative]), size=2
                    ),
                ),
                (
                    "bottom_right",
                    django_jsonform.models.fields.ArrayField(
                        base_field=models.FloatField(validators=[cvback.events.models.validate_relative]), size=2
                    ),
                ),
                ("inference_class", models.CharField(max_length=255)),
                ("confidence", models.FloatField(validators=[cvback.events.models.validate_relative])),
                (
                    "algorithm",
                    models.ForeignKey(
                        blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to="events.algorithm"
                    ),
                ),
                (
                    "inference_computer",
                    models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to="devices.inferencecomputer"),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Label",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("model", models.CharField(max_length=255)),
                ("label", models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name="InferenceDetectionClassification",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("added_date", models.DateTimeField(auto_now_add=True, verbose_name="date created")),
                (
                    "algorithm",
                    models.ForeignKey(
                        blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to="events.algorithm"
                    ),
                ),
                ("bounding_boxes", models.ManyToManyField(to="events.boundingbox")),
                (
                    "inference_computer",
                    models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to="devices.inferencecomputer"),
                ),
                ("labels", models.ManyToManyField(to="events.label")),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="InferenceClassification",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("added_date", models.DateTimeField(auto_now_add=True, verbose_name="date created")),
                (
                    "algorithm",
                    models.ForeignKey(
                        blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to="events.algorithm"
                    ),
                ),
                (
                    "inference_computer",
                    models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to="devices.inferencecomputer"),
                ),
                ("label", models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to="events.label")),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Event",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("added_date", models.DateTimeField(auto_now_add=True, verbose_name="date created")),
                ("camera", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="devices.camera")),
                (
                    "inference_classification",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="events.inferenceclassification",
                    ),
                ),
                (
                    "inference_detection_classification",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="events.inferencedetectionclassification",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="AreaOfInterest",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("added_date", models.DateTimeField(auto_now_add=True, verbose_name="date created")),
                ("added_modified", models.DateTimeField(auto_now=True, verbose_name="date modified")),
                ("enabled", models.BooleanField(default=True)),
                ("name", models.CharField(max_length=255)),
                (
                    "geometry",
                    django_jsonform.models.fields.ArrayField(
                        base_field=django_jsonform.models.fields.ArrayField(
                            base_field=models.FloatField(validators=[cvback.events.models.validate_relative]), size=2
                        ),
                        size=None,
                    ),
                ),
                ("description", models.TextField(blank=True, null=True)),
                ("camera", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="devices.camera")),
            ],
        ),
    ]
