# Generated by Django 4.2.5 on 2023-09-17 22:16

import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("devices", "0002_alter_camera_location_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="AreaOfInterest",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("added_date", models.DateTimeField(auto_now_add=True, verbose_name="date created")),
                ("added_modified", models.DateTimeField(auto_now=True, verbose_name="date modified")),
                ("enabled", models.BooleanField(default=True)),
                ("name", models.CharField(max_length=255)),
                (
                    "geometry",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=django.contrib.postgres.fields.ArrayField(base_field=models.FloatField(), size=2),
                        size=None,
                    ),
                ),
                ("camera", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="devices.camera")),
            ],
        ),
    ]
