# Generated by Django 4.2.5 on 2024-05-24 20:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("devices", "0007_camera_last_seen_online_camera_need_cleaning_and_more"),
        ("events", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="boundingbox",
            name="inference_computer",
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="devices.inferencecomputer"),
        ),
    ]
