# Generated by Django 4.2.5 on 2024-07-03 20:13

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):
    dependencies = [
        ("events", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="boundingbox",
            name="informed_date",
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name="date informed"),
        ),
        migrations.AddField(
            model_name="event",
            name="informed_date",
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name="date informed"),
        ),
        migrations.AddField(
            model_name="frame",
            name="added_date",
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name="date created"),
        ),
        migrations.AddField(
            model_name="frame",
            name="informed_date",
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name="date informed"),
        ),
        migrations.AddField(
            model_name="inferenceclassification",
            name="informed_date",
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name="date informed"),
        ),
        migrations.AddField(
            model_name="inferencedetectionclassification",
            name="informed_date",
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name="date informed"),
        ),
        migrations.AddField(
            model_name="inferencedetectionclassificationtracker",
            name="informed_date",
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name="date informed"),
        ),
        migrations.AddField(
            model_name="inferenceocr",
            name="informed_date",
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name="date informed"),
        ),
        migrations.AddField(
            model_name="video",
            name="added_date",
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name="date created"),
        ),
        migrations.AddField(
            model_name="video",
            name="informed_date",
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name="date informed"),
        ),
        migrations.AlterField(
            model_name="algorithm",
            name="added_date",
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name="date created"),
        ),
        migrations.AlterField(
            model_name="algorithm",
            name="version",
            field=models.CharField(
                max_length=30, validators=[django.core.validators.RegexValidator("^\\d{1,2}\\.\\d{1,2}\\.\\d{1,3}$")]
            ),
        ),
        migrations.AlterField(
            model_name="areaofinterest",
            name="added_date",
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name="date created"),
        ),
        migrations.AlterField(
            model_name="boundingbox",
            name="added_date",
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name="date created"),
        ),
        migrations.AlterField(
            model_name="event",
            name="added_date",
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name="date created"),
        ),
        migrations.AlterField(
            model_name="eventtype",
            name="added_date",
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name="date created"),
        ),
        migrations.AlterField(
            model_name="eventtype",
            name="version",
            field=models.CharField(
                max_length=30, validators=[django.core.validators.RegexValidator("^\\d{1,2}\\.\\d{1,2}\\.\\d{1,3}$")]
            ),
        ),
        migrations.AlterField(
            model_name="inferenceclassification",
            name="added_date",
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name="date created"),
        ),
        migrations.AlterField(
            model_name="inferenceclassification",
            name="label",
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="events.label"),
        ),
        migrations.AlterField(
            model_name="inferencedetectionclassification",
            name="added_date",
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name="date created"),
        ),
        migrations.AlterField(
            model_name="inferencedetectionclassificationtracker",
            name="added_date",
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name="date created"),
        ),
        migrations.AlterField(
            model_name="inferenceocr",
            name="added_date",
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name="date created"),
        ),
        migrations.AlterField(
            model_name="keyinferenceclassification",
            name="inferences",
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="events.inferenceclassification"),
        ),
        migrations.AlterField(
            model_name="lineofinterest",
            name="added_date",
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name="date created"),
        ),
    ]
