# Generated by Django 5.0.7 on 2024-07-09 20:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("events", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="boundingbox",
            name="algorithm",
        ),
        migrations.RemoveField(
            model_name="boundingbox",
            name="confidence",
        ),
        migrations.RemoveField(
            model_name="boundingbox",
            name="inference_computer",
        ),
        migrations.AddField(
            model_name="inferenceclassification",
            name="frame",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="%(class)s_inferences",
                to="events.frame",
            ),
        ),
        migrations.AddField(
            model_name="inferencedetectionclassification",
            name="frame",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="%(class)s_inferences",
                to="events.frame",
            ),
        ),
        migrations.AddField(
            model_name="inferencedetectionclassificationtracker",
            name="frame",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="%(class)s_inferences",
                to="events.frame",
            ),
        ),
        migrations.AddField(
            model_name="inferenceocr",
            name="frame",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="%(class)s_inferences",
                to="events.frame",
            ),
        ),
    ]
