# Generated by Django 4.2.5 on 2024-06-13 03:49

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("events", "0002_alter_boundingbox_inference_computer"),
    ]

    operations = [
        migrations.AddField(
            model_name="event",
            name="detection",
            field=models.CharField(default="estrella", max_length=100),
        ),
    ]
