# Generated by Django 4.2.5 on 2023-12-01 01:52

from django.db import migrations, models
import django.db.models.deletion
import django_jsonform.models.fields
import cvback.events.models


class Migration(migrations.Migration):
    dependencies = [
        ("devices", "0005_alter_camera_primary_stream"),
        ("events", "0003_alter_areaofinterest_geometry"),
    ]

    operations = [
        migrations.CreateModel(
            name="BoundingBox",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("added_date", models.DateTimeField(auto_now_add=True, verbose_name="date created")),
                (
                    "top_left",
                    django_jsonform.models.fields.ArrayField(
                        base_field=models.FloatField(validators=[cvback.events.models.validate_relative]), size=2
                    ),
                ),
                (
                    "bottom_right",
                    django_jsonform.models.fields.ArrayField(
                        base_field=models.FloatField(validators=[cvback.events.models.validate_relative]), size=2
                    ),
                ),
                ("type", models.CharField(max_length=255)),
                ("confidence", models.FloatField(validators=[cvback.events.models.validate_relative])),
            ],
        ),
        migrations.CreateModel(
            name="Event",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("added_date", models.DateTimeField(auto_now_add=True, verbose_name="date created")),
                ("camera", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="devices.camera")),
            ],
        ),
        migrations.CreateModel(
            name="TelegramAlert",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("added_date", models.DateTimeField(auto_now_add=True, verbose_name="date created")),
                ("telegram_user", models.CharField(max_length=255)),
                ("message", models.CharField(max_length=255)),
                ("events", models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to="events.event")),
            ],
        ),
        migrations.CreateModel(
            name="SMSAlert",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("added_date", models.DateTimeField(auto_now_add=True, verbose_name="date created")),
                ("phone_number", models.CharField(max_length=255)),
                ("message", models.CharField(max_length=255)),
                ("events", models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to="events.event")),
            ],
        ),
        migrations.CreateModel(
            name="Inference",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("added_date", models.DateTimeField(auto_now_add=True, verbose_name="date created")),
                (
                    "bounding_boxes",
                    models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to="events.boundingbox"),
                ),
                (
                    "inference_computer",
                    models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to="devices.inferencecomputer"),
                ),
            ],
        ),
        migrations.AddField(
            model_name="event",
            name="inference",
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to="events.inference"),
        ),
    ]
