# Generated by Django 4.2.5 on 2023-12-10 14:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("events", "0004_boundingbox_event_telegramalert_smsalert_inference_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Alert",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("added_date", models.DateTimeField(auto_now_add=True, verbose_name="date created")),
                ("alert_type", models.CharField(choices=[("telegram", "Telegram"), ("sms", "SMS")], max_length=50)),
                ("recipient", models.CharField(max_length=255)),
                ("message", models.CharField(max_length=255)),
                (
                    "related_event",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING, related_name="alerts", to="events.event"
                    ),
                ),
            ],
        ),
        migrations.RemoveField(
            model_name="telegramalert",
            name="events",
        ),
        migrations.AddField(
            model_name="areaofinterest",
            name="description",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="boundingbox",
            name="related_event",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="bounding_boxes",
                to="events.event",
            ),
        ),
        migrations.AddField(
            model_name="inference",
            name="related_event",
            field=models.ForeignKey(
                null=True, on_delete=django.db.models.deletion.CASCADE, related_name="inferences", to="events.event"
            ),
        ),
        migrations.DeleteModel(
            name="SMSAlert",
        ),
        migrations.DeleteModel(
            name="TelegramAlert",
        ),
    ]
