# Generated by Django 4.2.5 on 2024-02-13 02:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("devices", "0006_area_camera_area"),
        ("events", "0006_remove_boundingbox_related_event_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="InferenceClassification",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "kind",
                    models.CharField(
                        choices=[("dc", "Detection + classification"), ("cl", "Classification")], max_length=2
                    ),
                ),
                ("added_date", models.DateTimeField(auto_now_add=True, verbose_name="date created")),
                (
                    "inference_computer",
                    models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to="devices.inferencecomputer"),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="InferenceDetectionClassification",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "kind",
                    models.CharField(
                        choices=[("dc", "Detection + classification"), ("cl", "Classification")], max_length=2
                    ),
                ),
                ("added_date", models.DateTimeField(auto_now_add=True, verbose_name="date created")),
                ("bounding_boxes", models.ManyToManyField(to="events.boundingbox")),
                (
                    "inference_computer",
                    models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to="devices.inferencecomputer"),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Label",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("model", models.CharField(max_length=255)),
                ("label", models.CharField(max_length=255)),
            ],
        ),
        migrations.AlterField(
            model_name="alert",
            name="alert_type",
            field=models.CharField(
                choices=[("telegram", "Telegram"), ("sms", "SMS"), ("whatsapp_group", "Whatsapp group")], max_length=50
            ),
        ),
        migrations.AlterField(
            model_name="event",
            name="inference",
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="devices.inferencecomputer"),
        ),
        migrations.DeleteModel(
            name="Inference",
        ),
        migrations.AddField(
            model_name="inferencedetectionclassification",
            name="labels",
            field=models.ManyToManyField(to="events.label"),
        ),
        migrations.AddField(
            model_name="inferenceclassification",
            name="label",
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to="events.label"),
        ),
    ]
