# Generated by Django 4.2.5 on 2024-05-21 02:47

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("devices", "0007_camera_last_seen_online_camera_need_cleaning_and_more"),
        ("events", "0009_rename_labels_inferenceclassification_label_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Algorithm",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            ("dc", "Detection + classification model"),
                            ("cl", "Classification model"),
                            ("clccv", "Classification classic computer vision"),
                        ],
                        max_length=255,
                    ),
                ),
                ("added_date", models.DateTimeField(auto_now_add=True, verbose_name="date created")),
                ("name", models.CharField(max_length=30)),
                ("version", models.CharField(max_length=30)),
                ("repository", models.CharField(max_length=30, validators=[django.core.validators.URLValidator])),
            ],
        ),
        migrations.RenameField(
            model_name="boundingbox",
            old_name="type",
            new_name="inference_class",
        ),
        migrations.RemoveField(
            model_name="inferenceclassification",
            name="kind",
        ),
        migrations.RemoveField(
            model_name="inferencedetectionclassification",
            name="kind",
        ),
        migrations.AddField(
            model_name="boundingbox",
            name="inference_computer",
            field=models.ForeignKey(
                default=1, on_delete=django.db.models.deletion.DO_NOTHING, to="devices.inferencecomputer"
            ),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name="Alert",
        ),
        migrations.AddField(
            model_name="boundingbox",
            name="algorithm",
            field=models.ForeignKey(
                blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to="events.algorithm"
            ),
        ),
        migrations.AddField(
            model_name="inferenceclassification",
            name="algorithm",
            field=models.ForeignKey(
                blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to="events.algorithm"
            ),
        ),
        migrations.AddField(
            model_name="inferencedetectionclassification",
            name="algorithm",
            field=models.ForeignKey(
                blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to="events.algorithm"
            ),
        ),
    ]
