# Generated by Django 4.2.5 on 2023-09-19 22:51

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("devices", "0002_alter_camera_location_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="camera",
            name="primary_stream",
            field=models.CharField(
                default="rtsp://user:pass@local_ip:port/path",
                max_length=255,
                validators=[django.core.validators.URLValidator(schemes=["http", "https", "rtsp"])],
            ),
            preserve_default=False,
        ),
    ]
