# Generated by Django 4.2.5 on 2024-02-13 21:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("events", "0007_inferenceclassification_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="inferenceclassification",
            old_name="label",
            new_name="labels",
        ),
        migrations.RenameField(
            model_name="label",
            old_name="label",
            new_name="labels",
        ),
        migrations.RemoveField(
            model_name="event",
            name="inference",
        ),
        migrations.AddField(
            model_name="event",
            name="inference_classification",
            field=models.ForeignKey(
                blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to="events.inferenceclassification"
            ),
        ),
        migrations.AddField(
            model_name="event",
            name="inference_detection_classification",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="events.inferencedetectionclassification",
            ),
        ),
    ]
