# Generated by Django 4.2.5 on 2024-02-19 02:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("events", "0008_rename_label_inferenceclassification_labels_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="inferenceclassification",
            old_name="labels",
            new_name="label",
        ),
        migrations.RenameField(
            model_name="label",
            old_name="labels",
            new_name="label",
        ),
        migrations.AlterField(
            model_name="alert",
            name="related_event",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, related_name="alerts", to="events.event"
            ),
        ),
    ]
