#!/bin/bash

set -o errexit
set -o pipefail
set -o nounset

if [ "$DJANGO_EXEC_MIGRATE" == "true" ]; then
    python manage.py migrate
fi

if [ "$DJANGO_EXEC_CREATE_SU" == "true" ]; then
    python manage.py createsuperuser --noinput
fi

if [ "$DJANGO_EXEC_COLLECTSTATIC" == "true" ]; then
    python manage.py collectstatic --noinput
fi

exec python manage.py runserver_plus 0.0.0.0:$DJANGO_PORT
