#!/bin/bash

set -o errexit
set -o pipefail
set -o nounset

if [ "$DJANGO_EXEC_MIGRATE" == "true" ]; then
    python manage.py migrate
fi

if [ "$DJANGO_EXEC_CREATE_SU" == "true" ]; then
    python manage.py createsuperuser --noinput
fi

if [ "$DJANGO_EXEC_COLLECTSTATIC" == "true" ]; then
    python manage.py collectstatic --noinput
fi

exec /usr/local/bin/gunicorn --preload --workers=1 --threads=8 --timeout=0 --bind=0.0.0.0:$DJANGO_PORT --chdir=/app config.wsgi:application
