# Generated by Django 4.2.5 on 2023-09-17 22:16

import django.contrib.gis.db.models.fields
import django.contrib.gis.geos.point
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("devices", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="camera",
            name="location",
            field=django.contrib.gis.db.models.fields.PointField(
                default=django.contrib.gis.geos.point.Point(-70.60601882155144, -33.41260825941644, srid=4326),
                srid=4326,
            ),
        ),
        migrations.AlterField(
            model_name="inferencecomputer",
            name="location",
            field=django.contrib.gis.db.models.fields.PointField(
                default=django.contrib.gis.geos.point.Point(-70.69441297829056, -33.358564373936446, srid=4326),
                srid=4326,
            ),
        ),
    ]
