# Generated by Django 4.2.5 on 2023-11-20 22:53

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("devices", "0003_camera_primary_stream"),
    ]

    operations = [
        migrations.AlterField(
            model_name="camera",
            name="primary_stream",
            field=models.CharField(
                max_length=1024, validators=[django.core.validators.URLValidator(schemes=["http", "https", "rtsp"])]
            ),
        ),
    ]
