# Generated by Django 4.2.5 on 2023-11-22 21:14

import django.core.validators
from django.db import migrations
import encrypted_field.fields


class Migration(migrations.Migration):
    dependencies = [
        ("devices", "0004_alter_camera_primary_stream"),
    ]

    operations = [
        migrations.AlterField(
            model_name="camera",
            name="primary_stream",
            field=encrypted_field.fields.EncryptedField(
                max_length=1024, validators=[django.core.validators.URLValidator(schemes=["http", "https", "rtsp"])]
            ),
        ),
    ]
