# Generated by Django 4.2.5 on 2024-05-21 02:47

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("devices", "0006_area_camera_area"),
    ]

    operations = [
        migrations.AddField(
            model_name="camera",
            name="last_seen_online",
            field=models.DateTimeField(auto_now=True, verbose_name="last seen online"),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="camera",
            name="need_cleaning",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="camera",
            name="need_physical_maintenance",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="camera",
            name="need_replacement",
            field=models.BooleanField(default=False),
        ),
    ]
