# Generated by Django 4.2.5 on 2024-06-13 01:29

import django.contrib.gis.db.models.fields
import django.contrib.gis.geos.point
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("devices", "0007_camera_last_seen_online_camera_need_cleaning_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="area",
            name="area_location",
            field=django.contrib.gis.db.models.fields.PointField(
                default=django.contrib.gis.geos.point.Point(-70.6761237, -33.56396059, srid=4326), srid=4326
            ),
        ),
        migrations.AlterField(
            model_name="camera",
            name="location",
            field=django.contrib.gis.db.models.fields.PointField(
                default=django.contrib.gis.geos.point.Point(-70.6561237, -33.4396059, srid=4326), srid=4326
            ),
        ),
    ]
