# Generated by Django 4.2.5 on 2024-06-23 23:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("events", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Alert",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("added_date", models.DateTimeField(auto_now_add=True, verbose_name="date created")),
                (
                    "alert_type",
                    models.CharField(
                        choices=[("telegram", "Telegram"), ("sms", "SMS"), ("whatsapp_group", "Whatsapp group")],
                        max_length=50,
                    ),
                ),
                ("recipient", models.CharField(max_length=255)),
                ("message", models.CharField(max_length=255)),
                (
                    "related_event",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="alerts_from_alerts_unique",
                        to="events.event",
                    ),
                ),
            ],
        ),
    ]
