# Generated by Django 4.2.5 on 2024-05-24 02:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("events", "0010_algorithm_rename_type_boundingbox_inference_class_and_more"),
        ("alerts", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="alert",
            name="related_event",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.DO_NOTHING, related_name="alerts_from_alerts", to="events.event"
            ),
        ),
    ]
